services:
  collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
    - ./otel-config.yaml:/etc/otelcol-contrib/config.yaml
    - rfp-analyzer-logs:/usr/src/app
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317"
    networks:
      - default
    depends_on:
      rfp-analyzer:
        condition: service_healthy

  loki:
    image: grafana/loki:latest
    volumes:
      - loki-data:/loki
      - ./loki.yaml:/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - default

  rfp-analyzer:
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 5s
      start_interval: 5s
    volumes:
    - rfp-analyzer-logs:/app:rw
    ports:
    - "8000:8000"
    networks:
    - default

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  rfp-analyzer-logs:
  loki-data:
  grafana-data: