receivers:
  filelog:
    include: [/usr/src/app/*.log]
    operators:
      - type: json_parser
        timestamp:
          parse_from: attributes.asctime
          layout: '%Y-%m-%dT%H:%M:%S'
        severity:
          parse_from: attributes.levelname
        service_name:
          parse_from: attributes.name
          target: service.name
        message:
          parse_from: attributes.message
processors:
  batch:
    timeout: 5s
    send_batch_size: 1
exporters:
  debug:
    verbosity: detailed
  otlphttp:
    endpoint: http://loki:3100/otlp
service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [debug, otlphttp]